// Visual slide for each step (rendered to public/screens/<id>.jpg by scripts/build-slides.ts).
// `hl` = index of the item the narration focuses on; its box becomes the step's pulsing highlight.
// Text on slides is short on purpose — the narration carries the explanation.

export type Item = { icon?: string; title: string; text?: string; tag?: string };
export type Slide =
  | { kind: "arch"; box: string; note?: string }
  | { kind: "golden"; targets: string[]; note?: string }
  | { kind: "cards"; items: Item[]; cols?: number; hl?: number; note?: string }
  | { kind: "flow"; items: Item[]; hl?: number; note?: string }
  | { kind: "stats"; items: { value: string; label: string; sub?: string }[]; hl?: number; note?: string }
  | { kind: "table"; head: string[]; rows: string[][]; hl?: number; note?: string }
  | { kind: "compare"; left: { title: string; items: string[] }; right: { title: string; items: string[] }; hl?: 0 | 1; note?: string };

export const SLIDES: Record<string, Slide> = {
  "0.1": {
    kind: "cards",
    cols: 3,
    hl: 1,
    items: [
      { icon: "🗺️", title: "תמונה כללית", text: "למה עוברים ומה עובר" },
      { icon: "🧩", title: "שלוש מערכות", text: "הנהלת חשבונות · רווחה · גבייה" },
      { icon: "🛤️", title: "8 שלבי מעבר", text: "עם שער אישור לכל שלב" },
    ],
    note: "מעבר מאקסס ל־WEB · מסלול לימוד מדורג",
  },
  "1.1": {
    kind: "compare",
    hl: 1,
    left: { title: "היום — Access", items: ["מסכים, קוד וטבלאות בקובצי Access", "עבודה דרך שולחן עבודה מרוחק (RDS)", "תלות בשרתי קבצים ובתחנות משתמש"] },
    right: { title: "היעד — WEB", items: ["מסכי WEB למשתמש", "שכבת שירותים וכללים עסקיים", "מאגרי מידע ומסמכים מנוהלים"] },
    note: "החוברת מפרידה בין שימור המערכת הקיימת בזמן המעבר לבין אפיון מערכת WEB חדשה",
  },
  "1.2": {
    kind: "cards",
    cols: 3,
    hl: 2,
    items: [
      { icon: "📒", title: "הנהלת חשבונות", tag: "HNS", text: "HNS_COMP ו־HNS_MAIN · רמדור · Goldnet · אתרי ממשלה" },
      { icon: "🤝", title: "רווחה", tag: "RVC", text: "שירותי מסמכים ו־PDF · אתר משרד הרווחה" },
      { icon: "💳", title: "גבייה", tag: "GVIA", text: "שוברים · חשבוניות · אשראי · מס״ב · SMS ודוא״ל" },
    ],
    note: "הגבייה — המערכת עם הכי הרבה ממשקים",
  },
  "1.3": {
    kind: "stats",
    hl: 3,
    items: [
      { value: "22", label: "ממצאי רשת" },
      { value: "44", label: "ממצאי התקנות" },
      { value: "134", label: "ממצאי נתונים" },
      { value: "433", label: "ממצאי קוד" },
    ],
    note: "סה״כ 633 הופעות בדוחות — לא רכיבים ייחודיים ולא אומדן פיתוח",
  },
  "1.4": {
    kind: "cards",
    cols: 4,
    hl: 0,
    items: [
      { icon: "✅", title: "מתועד בדוח", text: "מופיע במקור" },
      { icon: "🔎", title: "הסקה לאימות", text: "נגזר משמות רכיבים" },
      { icon: "💡", title: "מוצע", text: "יעד או בדיקה חדשים" },
      { icon: "❔", title: "חסר", text: "לא נמסר" },
    ],
    note: "רק מה שמתועד הוא עובדה",
  },
  "1.5": {
    kind: "compare",
    hl: 1,
    left: { title: "גיליונות מקרא — מצב קיים", items: ["1. קישורים ומיקומים חיצוניים", "2. התקנות ותוכנות נדרשות", "3. נתונים בטבלאות", "4. עדכונים נדרשים בקוד"] },
    right: { title: "גיליונות WEB — תכנון", items: ["מה ידוע על המצב הקיים", "יעד WEB — הצעה לאישור", "מה יש לברר / איך בודקים", "מקור בדוח · בסיס המידע"] },
  },
  "2.1": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "💻", title: "תחנת המשתמש", text: "כוננים מקומיים" },
      { icon: "🔁", title: "\\\\tsclient", text: "הפניית כוננים ב־RDP" },
      { icon: "🖥️", title: "שרת RDS", text: "המערכת רצה כאן" },
    ],
    note: "ב־WEB: כל תלות בתחנה הופכת לפעולה מפורשת — העלאה או הורדה של קובץ",
  },
  "2.2": {
    kind: "cards",
    cols: 2,
    hl: 1,
    items: [
      { icon: "🗂️", title: "נתיב UNC", text: "\\\\שם-שרת\\תיקייה — תיקייה משותפת בשרת קבצים" },
      { icon: "💽", title: "כונן ממופה", text: "M:  Z:  O: — אות כונן שמחוברת לתיקיית רשת" },
    ],
    note: "בשרת החדש — אותה אות, לאותו יעד",
  },
  "2.3": {
    kind: "compare",
    hl: 0,
    left: { title: "נתיב קשיח", items: ["כתוב ישירות בקוד", "שינוי = שינוי קוד", "או פריסה באותו נתיב בדיוק"] },
    right: { title: "פרמטר בטבלה", items: ["נשמר במסד (param, paramnext, usr)", "שינוי = UPDATE לערך", "בלי לגעת בקוד"] },
  },
  "2.4": {
    kind: "cards",
    cols: 3,
    hl: 2,
    items: [
      { icon: "🧱", title: "COM / ActiveX", text: "Word · Excel · Outlook · SOAP מופעלים מהקוד" },
      { icon: "📝", title: "regsvr32", text: "רישום רכיב dll/ocx בהרשאות מנהל" },
      { icon: "⚖️", title: "32 / 64 ביט", text: "Access והרכיבים — באותה גרסה" },
    ],
  },
  "2.5": {
    kind: "table",
    hl: 3,
    head: ["מושג", "משמעות"],
    rows: [
      ["HTTPS / TLS", "תקשורת מוצפנת — תעודה תקפה ופורט פתוח"],
      ["פורטים", "443 אתרים · 11821–11837 שרתי EPR · 21 FTP"],
      ["Allowlist · DNS", "יעדים מותרים ביציאה · תרגום שם שרת לכתובת"],
      ["FTP / FTPS / SFTP", "FTP לא מוצפן — עדיף FTPS או SFTP"],
    ],
  },
  "2.6": {
    kind: "cards",
    cols: 3,
    hl: 0,
    items: [
      { icon: "🎯", title: "מקור אמת", text: "המערכת האחראית לערך המחייב" },
      { icon: "🧪", title: "בדיקות קבלה", text: "תרחישים שבעלי המערכת מאשרים" },
      { icon: "🔄", title: "הסבה וחזרה לאחור", text: "העברת נתונים · נוהל שיקום" },
      { icon: "🚦", title: "פיילוט ושער אישור", text: "הפעלה מצומצמת · נקודת אישור" },
      { icon: "🔌", title: "API / ממשק", text: "ממשק אוטומטי ≠ קישור לאתר" },
      { icon: "🧼", title: "SOAP", text: "תקן ישן מבוסס XML" },
    ],
  },
  "3.1": {
    kind: "stats",
    hl: 3,
    items: [
      { value: "4", label: "רשת" },
      { value: "13", label: "התקנות" },
      { value: "22", label: "נתונים" },
      { value: "50", label: "קוד" },
    ],
    note: "HNS — סה״כ 89 פריטים · שני מסדים: HNS_COMP ו־HNS_MAIN",
  },
  "3.2": {
    kind: "cards",
    cols: 2,
    hl: 2,
    items: [
      { icon: "📁", title: "נתיבים קשיחים בכונן C", text: "49 שורות קוד — התיקיות חייבות להתקיים בשרת החדש" },
      { icon: "✉️", title: "ClickYes", text: "אישור אוטומטי לאזהרת Outlook — בנתיב קשיח" },
      { icon: "📤", title: "רמדור ב־FTP", text: "eprftp1.exe · פורט 21 · לא מוצפן" },
      { icon: "🗄️", title: "מסמכים בשרת הקבצים", text: "1,005 הפניות בטבלת doclist" },
    ],
  },
  "3.3": {
    kind: "cards",
    cols: 3,
    hl: 2,
    items: [
      { icon: "📤", title: "רמדור", text: "העברת קבצים" },
      { icon: "🏦", title: "Goldnet / BusinessNet", text: "שיגור קבצים" },
      { icon: "🏛️", title: "ממשלה ובנק", text: "רשות המסים · הלמ״ס · ביטוח לאומי · משרד החינוך · בנק לאומי" },
    ],
    note: "קישור שהמשתמש פותח ≠ ממשק אוטומטי",
  },
  "3.4": {
    kind: "compare",
    hl: 1,
    left: { title: "מתועד בדוח", items: ["ממשקים", "דוחות והדפסה", "קבצים ופרמטרים"] },
    right: { title: "חסר לאפיון הליבה", items: ["פקודות יומן וחשבונות", "תקופות ונעילת תקופה", "התאמות וכללי אישור"] },
    note: "ליבת הנהלת החשבונות — פרק אפיון עסקי נפרד לפני אומדן",
  },
  "4.1": {
    kind: "stats",
    hl: 3,
    items: [
      { value: "8", label: "רשת" },
      { value: "13", label: "התקנות" },
      { value: "19", label: "נתונים" },
      { value: "207", label: "קוד" },
    ],
    note: "RVC — סה״כ 247 פריטים · טפסים משפטיים, ועדות וזימונים",
  },
  "4.2": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "📂", title: "היום", text: "פתיחה וכתיבה לכונן התחנה" },
      { icon: "🔁", title: "129 שורות קוד", text: "הפניות דרך \\\\tsclient" },
      { icon: "🌐", title: "ב־WEB", text: "פעולה מפורשת: העלאה / הורדה" },
    ],
  },
  "4.3": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "🧼", title: "SOAP Toolkit 3.0", text: "לא נתמך" },
      { icon: "🔍", title: "לאתר בשרת הישן", text: "לפני המיגרציה" },
      { icon: "🧭", title: "למפות פעולה עסקית", text: "להחליף או לעטוף בשירות" },
    ],
    note: "העתקת DLL אינה אפיון WEB",
  },
  "4.4": {
    kind: "cards",
    cols: 3,
    hl: 0,
    items: [
      { icon: "🗄️", title: "~162 אלף הפניות", text: "מסמכי תיק בשרת הקבצים" },
      { icon: "📝", title: "תבניות מכתבים", text: "מרשם תבניות מרכזי" },
      { icon: "📎", title: "סריקה וצרופות", text: "העלאה ושיוך עם אישור משתמש" },
    ],
    note: "הפניות ≠ קבצים ייחודיים",
  },
  "4.5": {
    kind: "table",
    hl: 0,
    head: ["רכיב", "הצעה לאישור"],
    rows: [
      ["מטריצת הרשאות", "לפי תפקיד, תיק ופעולה"],
      ["יומן פעולות", "צפייה, שינוי וייצוא"],
      ["טקסט חופשי", "מדיניות שימור עם בעל המידע"],
      ["בדיקה", "משתמש מורשה מול לא מורשה"],
    ],
  },
  "5.1": {
    kind: "stats",
    hl: 3,
    items: [
      { value: "10", label: "רשת" },
      { value: "18", label: "התקנות" },
      { value: "93", label: "נתונים" },
      { value: "176", label: "קוד" },
    ],
    note: "GVIA — סה״כ 297 פריטים · כולל GviaExt",
  },
  "5.2": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "🔎", title: "איתור", text: "משלם / חיוב" },
      { icon: "🧾", title: "שובר", text: "הפקה" },
      { icon: "💳", title: "תשלום", text: "מלא · חלקי · כשל" },
      { icon: "📌", title: "אסמכתה", text: "" },
      { icon: "📊", title: "התאמה ודיווח", text: "" },
    ],
    note: "תרחיש מוצע — הסקה לאימות",
  },
  "5.3": {
    kind: "compare",
    hl: 0,
    left: { title: "סליקת אשראי", items: ["CreditGuard", "מתאם תשלומים בצד השרת", "הפרדת בדיקה וייצור", "מניעת חיוב כפול"] },
    right: { title: "מס״ב", items: ["הפקה ואישור", "משלוח וקליטת תשובה", "מעקב מצב לכל אצווה", "מניעת קליטה כפולה"] },
  },
  "5.4": {
    kind: "cards",
    cols: 3,
    hl: 0,
    items: [
      { icon: "🗄️", title: "~595 אלף הפניות", text: "מסמכי דוא״ל בשרת הקבצים" },
      { icon: "🔗", title: "קישורים שנשלחו", text: "חשבוניות ושוברים — לשמר פתיחה" },
      { icon: "📨", title: "דוא״ל ו־SMS", text: "תבניות · תור · מעקב מסירה" },
    ],
    note: "595 אלף הפניות ≠ 595 אלף קבצים",
  },
  "5.5": {
    kind: "compare",
    hl: 1,
    left: { title: "היום", items: ["פרמטר בטבלה מצביע לשרת פיתוח", "כתובות קשיחות בלוגיקה", "דוגמאות כתובות בדוח"] },
    right: { title: "ב־WEB", items: ["מרשם כתובות לבדיקה", "מרשם כתובות לייצור", "אישור בעל השירות לפני חיבור"] },
  },
  "5.6": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "💳", title: "גבייה", text: "תקבולים · ביטולים" },
      { icon: "🔌", title: "ממשק מאושר", text: "מזהה פעולה · אסמכתה · סכום · תאריך · סטטוס" },
      { icon: "📒", title: "הנהלת חשבונות", text: "רישום והתאמה" },
    ],
    note: "קיים היום? ממשק אוטומטי, קובץ או הזנה ידנית — לברר",
  },
  "6.1": {
    kind: "flow",
    hl: 0,
    items: [
      { tag: "1", title: "אישור תמונת המצב", text: "קטלוג יכולות מוסכם" },
      { tag: "2", title: "השלמת אפיון עסקי", text: "טריגר · קלט · כללים · חריגים" },
      { tag: "3", title: "מיפוי נתונים וממשקים", text: "" },
      { tag: "4", title: "הוכחת היתכנות", text: "" },
    ],
  },
  "6.2": {
    kind: "flow",
    hl: 2,
    items: [
      { tag: "1", title: "אישור תמונת המצב", text: "" },
      { tag: "2", title: "השלמת אפיון עסקי", text: "" },
      { tag: "3", title: "מיפוי נתונים וממשקים", text: "מקור אמת · תכנית הסבה" },
      { tag: "4", title: "תכנון והוכחת היתכנות", text: "תהליך מייצג · תלויות קריטיות" },
    ],
  },
  "6.3": {
    kind: "flow",
    hl: 0,
    items: [
      { tag: "5", title: "פיתוח והסבת ניסיון", text: "דוח התאמות · חריגים · עברית" },
      { tag: "6", title: "בדיקות קבלה ופיילוט", text: "מערכת רושמת אחת לכל פעולה" },
      { tag: "7", title: "מעבר מבוקר", text: "" },
      { tag: "8", title: "ייצוב וסיום Access", text: "" },
    ],
  },
  "6.4": {
    kind: "flow",
    hl: 2,
    items: [
      { tag: "5", title: "פיתוח והסבת ניסיון", text: "" },
      { tag: "6", title: "בדיקות קבלה ופיילוט", text: "" },
      { tag: "7", title: "מעבר מבוקר", text: "גיבוי · עצירת כתיבה · חזרה לאחור" },
      { tag: "8", title: "ייצוב וסיום Access", text: "ניטור · הדרכה · שימור היסטוריה" },
    ],
  },
  "6.5": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "🖥️", title: "מסכי WEB", text: "למשתמש" },
      { icon: "⚙️", title: "שירותים וכללים עסקיים", text: "" },
      { icon: "🗄️", title: "מאגרי מידע ומסמכים", text: "" },
    ],
    note: "ממשקי ספקים, תשלומים והודעות — בנפרד · טכנולוגיה ואירוח טרם נבחרו",
  },
  "6.6": {
    kind: "cards",
    cols: 2,
    hl: 3,
    items: [
      { icon: "👤", title: "בעלות והיקף", text: "מי בעל המערכת · מה בגרסה הראשונה" },
      { icon: "🧭", title: "גבולות בין המערכות", text: "מקור אמת · מזהה פעולה" },
      { icon: "🤝", title: "ספקים ומערכת יעד", text: "קוד · מפרטים · סביבות בדיקה" },
      { icon: "📈", title: "נפחים ויעדי שירות", text: "בלעדיהם אין אומדן אמין" },
    ],
  },
  "7.1": {
    kind: "cards",
    cols: 2,
    hl: 0,
    items: [
      { icon: "🔢", title: "הפניות ≠ קבצים", text: "כמות הפניות אינה כמות קבצים ייחודיים" },
      { icon: "🚫", title: "בלי החלפה גורפת", text: "לא בלוגים ולא בקישורים שנשלחו" },
      { icon: "🏷️", title: "שם ≠ תהליך", text: "שם שדה או קובץ אינו מוכיח תהליך" },
      { icon: "🔒", title: "המקור נשמר", text: "גיליונות המקרא — ללא שינוי" },
    ],
  },
  "7.2": {
    kind: "table",
    hl: 3,
    head: ["שלב", "משך", "סיום כאשר"],
    rows: [
      ["תמונה כללית", "יום 1", "מסבירים במשפט מה כל מערכת עושה"],
      ["מושגי יסוד", "ימים 2–3", "כל המונחים במילון מוכרים"],
      ["HNS · RVC · GVIA", "ימים 4–10", "עונים על שאלות כל מערכת"],
      ["הטמעה", "ימים 11–12", "3 סיכונים ו־3 שאלות לכל בעל מערכת"],
    ],
    note: "ואחריה: סדנת תהליך עם משתמש מפתח מכל מערכת",
  },

  // ---- architecture deep-dive (diagram regions) ----
  "8.1": { kind: "arch", box: "legacy" },
  "8.2": { kind: "arch", box: "rdp" },
  "8.3": { kind: "arch", box: "terminal" },
  "8.4": { kind: "arch", box: "access" },
  "8.5": { kind: "arch", box: "vm" },
  "8.6": { kind: "arch", box: "sql" },
  "8.7": { kind: "arch", box: "fileServer" },
  "8.8": { kind: "arch", box: "external" },
  "8.9": { kind: "arch", box: "pains" },
  "9.1": { kind: "arch", box: "target" },
  "9.2": { kind: "arch", box: "browser" },
  "9.3": { kind: "arch", box: "cloud" },
  "9.4": { kind: "arch", box: "api" },
  "9.5": { kind: "arch", box: "bff" },
  "9.6": { kind: "arch", box: "bffMsg" },
  "9.7": { kind: "arch", box: "queue" },
  "9.8": { kind: "arch", box: "backend" },
  "9.9": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "📦", title: "קונטיינר", text: "קוד + כל מה שהוא צריך כדי לרוץ" },
      { icon: "🛳️", title: "ECS", text: "מריץ ומנהל את הקונטיינרים" },
      { icon: "⚡", title: "Fargate", text: "בלי שרתים לנהל · גדל לפי עומס" },
    ],
    note: "כל מיקרו־שירות רץ בקונטיינר משלו, ונפרס ומוגדל בנפרד",
  },
  "9.10": { kind: "arch", box: "rds" },
  "9.11": { kind: "arch", box: "stackDb" },
  "9.12": { kind: "arch", box: "redis" },
  "9.13": { kind: "arch", box: "s3" },
  "9.14": { kind: "arch", box: "secrets" },
  "9.15": { kind: "arch", box: "agent" },
  "9.16": { kind: "arch", box: "scanner" },
  "10.1": {
    kind: "compare",
    hl: 1,
    left: { title: "היום", items: ["שרת Terminal ו־RDP", "התקנות על כל תחנה", "עדכון = עבודה על השרת"] },
    right: { title: "Browser-first", items: ["דפדפן בלבד", "חומרה מקומית רק דרך Local Agent", "עדכון אחד לכל המשתמשים"] },
  },
  "10.2": {
    kind: "compare",
    hl: 0,
    left: { title: "BFF — כן", items: ["אימות והרשאות", "זיהוי הרשות וניתוב", "הרכבת תשובה למסך"] },
    right: { title: "BFF — לא", items: ["חישובי חיוב", "אישור תשלום", "כל כלל עסקי"] },
    note: "לוגיקה עסקית גרה רק בשירותי ה־Backend",
  },
  "10.3": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "🔐", title: "בקשה", text: "נושאת את זהות הרשות" },
      { icon: "🧭", title: "מישור הבקרה", text: "קובע את מסד הרשות" },
      { icon: "🛡️", title: "שירות", text: "בודק שייכות בכל פעולה" },
      { icon: "🗄️", title: "מסד הרשות", text: "נתונים מבודדים" },
    ],
    note: "גם טעות בקוד לא אמורה לחשוף נתונים בין רשויות",
  },
  "10.4": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "🖱️", title: "בקשה", text: "הפק 5,000 שוברים" },
      { icon: "📬", title: "תור", text: "הבקשה נשמרת" },
      { icon: "⚙️", title: "עבודה ברקע", text: "ניסיון חוזר בכשל" },
      { icon: "🔔", title: "עדכון", text: "הסתיים — להורדה" },
    ],
    note: "המסך לא נתקע · ניתוק לא קוטע · הרבה פעולות במקביל",
  },
  "10.5": {
    kind: "compare",
    hl: 0,
    left: { title: "מישור הבקרה — Control Plane", items: ["RDS PostgreSQL אחד", "רשויות, הגדרות, משתמשים", "לאיזה מסד שייכת כל רשות"] },
    right: { title: "מישור הנתונים — Data Plane", items: ["SQL Server לכל רשות", "חיובים, תשלומים, תיקים", "היסטוריה קיימת נשמרת"] },
  },
  "11.1": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "🌐", title: "דפדפן", text: "הזדהות" },
      { icon: "🚪", title: "BFF", text: "אימות" },
      { icon: "🧭", title: "מישור הבקרה", text: "רשות · הרשאות · מסד" },
      { icon: "⚡", title: "Redis", text: "הגדרות במטמון" },
      { icon: "🔑", title: "Secrets Manager", text: "פרטי חיבור" },
    ],
  },
  "11.2": {
    kind: "flow",
    hl: 3,
    items: [
      { icon: "🌐", title: "דפדפן", text: "פותח מסך יתרות" },
      { icon: "🚪", title: "BFF", text: "הרשאה וניתוב" },
      { icon: "💳", title: "שירות גבייה", text: "" },
      { icon: "⚡", title: "Redis", text: "יש במטמון?" },
      { icon: "🗄️", title: "מסד הרשות", text: "אם לא — קורא ושומר" },
    ],
  },
  "11.3": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "💳", title: "שירות תשלומים", text: "אימות מול הסליקה" },
      { icon: "🗄️", title: "שמירה", text: "עם מזהה פעולה ייחודי" },
      { icon: "📣", title: "SNS", text: "אירוע: תשלום נקלט" },
      { icon: "🧾", title: "המגיבים", text: "קבלה · הודעה · הנהלת חשבונות" },
    ],
  },
  "11.4": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "🖱️", title: "בקשה", text: "הפקה בכמות" },
      { icon: "📬", title: "SQS", text: "הבקשה בטיפול" },
      { icon: "⚙️", title: "Fargate", text: "מפיק ברקע" },
      { icon: "🪣", title: "S3", text: "הקבצים נשמרים" },
      { icon: "🔔", title: "עדכון", text: "קישור זמני להורדה" },
    ],
  },
  "11.5": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "🖱️", title: "סרוק", text: "לחיצה בדפדפן" },
      { icon: "🛰️", title: "SignalR", text: "פקודה לסוכן" },
      { icon: "🖨️", title: "Local Agent", text: "מפעיל את הסורק" },
      { icon: "🪣", title: "S3", text: "קובץ משויך לתיק" },
    ],
  },
  "11.6": {
    kind: "flow",
    hl: 1,
    items: [
      { icon: "⚙️", title: "שירות", text: "צריך לשלוח הודעה" },
      { icon: "📬", title: "תור הודעות", text: "תבנית · נמענים" },
      { icon: "🔑", title: "Secrets Manager", text: "מפתח הספק" },
      { icon: "📨", title: "ספק SMS / דואר", text: "סטטוס מסירה" },
    ],
    note: "ספק לא זמין? ההודעה נשארת בתור ונשלחת שוב — בלי כפילות",
  },
  "12.1": { kind: "arch", box: "wave1" },
  "12.2": { kind: "arch", box: "wave2" },
  "12.3": { kind: "arch", box: "wave3" },
  "12.4": {
    kind: "table",
    hl: 2,
    head: ["היום", "ביעד"],
    rows: [
      ["RDP ושרת Terminal", "דפדפן — Angular"],
      ["טפסי Access ו־VBA", "מסכי WEB ושירותי Backend"],
      ["גישה ישירה ל־SQL Server", "גישה דרך שירותים בלבד"],
      ["שרת קבצים (UNC)", "S3"],
      ["סיסמאות בקוד ובטבלאות", "Secrets Manager"],
      ["\\tsclient", "Local Agent"],
    ],
  },
  "12.5": { kind: "arch", box: "stack" },

  // ---- the joker module: the golden slide (docs/golden-slide/golden-slide.html) ----
  "13.1": { kind: "golden", targets: ["b-user", "arrow-1"] },
  "13.2": { kind: "golden", targets: ["b-angular", "b-bff", "b-billing"] },
  "13.3": { kind: "golden", targets: ["arrow-1", "arrow-2", "arrow-3", "arrow-4", "arrow-5", "b-billing", "b-control", "b-sql"] },
  "13.4": { kind: "golden", targets: ["b-bff"] },
  "13.5": { kind: "golden", targets: ["arrow-6", "arrow-7", "arrow-8", "arrow-9", "arrow-10", "b-queue", "b-worker"] },
  "13.6": { kind: "golden", targets: ["arrow-11", "arrow-12", "b-status"] },
  "13.7": { kind: "golden", targets: ["arrow-14", "b-legacy", "b-sql"] },
  "13.8": { kind: "golden", targets: ["b-support"] },
  "13.9": {
    kind: "table",
    hl: 1,
    head: ["עמודה בטבלה", "מה כותבים בה"],
    rows: [
      ["חץ ופעולה עסקית", "2 · חיפוש חייב"],
      ["מה בונים", "מסך · BFF · שירות · תשתית"],
      ["חוזה המידע", "GET /api/payers?query= → רשימה"],
      ["איך בודקים", "בלי הזדהות — נדחה; עם — רשימה"],
      ["פתוח", "שיטת ההזדהות — לארכיטקט"],
    ],
    note: "רשות מהזהות · מזהה מעקב בכל בקשה · בלי פעולה כפולה",
  },
  "13.10": {
    kind: "flow",
    hl: 2,
    items: [
      { icon: "📝", title: "הגדרת התנהגות", text: "דוגמאות אמיתיות מאקסס" },
      { icon: "✂️", title: "משימה קטנה", text: "אחת בכל פעם" },
      { icon: "🤖", title: "ה-AI בונה", text: "הקשר + מה אסור" },
      { icon: "✅", title: "אתם בודקים", text: "בדפדפן, לפי רשימה" },
      { icon: "🏛️", title: "ארכיטקט מחליט", text: "כל שאלה פתוחה" },
    ],
  },
  "13.11": {
    kind: "table",
    hl: 4,
    head: ["משימה", "מה מוכיחים"],
    rows: [
      ["0 · תיעוד ההתנהגות", "מה קורה היום באקסס"],
      ["1–2 · שלד מדומה + בדיקות", "מסך ← BFF ← שירות, כללים נכונים"],
      ["3 · מסד בדיקה, קריאה בלבד", "אותם נתונים כמו באקסס"],
      ["4 · הזדהות ורשות", "רשות אחרת חסומה"],
      ["5–6 · ברקע: מדומה ← אמיתי", "באמת עובד מקצה לקצה"],
      ["7 · מתג לרשות הניסוי", "אפשר לחזור לאקסס"],
    ],
  },
  "13.12": {
    kind: "compare",
    hl: 0,
    left: { title: "מבקשים", items: ["מסך חיפוש + BFF + שירות", "5 חייבים מדומים", "מזהה מעקב בכל בקשה", "הוראות הפעלה + רשימת בדיקה"] },
    right: { title: "אוסרים", items: ["מסד אמיתי או ענן", "סיסמאות בקוד", "רכיבים נוספים (תור, S3)", "החלפת טכנולוגיות בלי לשאול"] },
  },
  "13.13": {
    kind: "cards",
    cols: 2,
    hl: 1,
    items: [
      { icon: "🚪", title: "שני BFF?", text: "רכיב אחד או שניים" },
      { icon: "🔔", title: "סטטוס למסך", text: "איפה נשמר ואיך מגיע" },
      { icon: "📬", title: "מה עובר בתור", text: "ומה ישירות לשירות" },
      { icon: "🧭", title: "Control Plane", text: "מה נשמר בו בדיוק" },
      { icon: "🗄️", title: "מסדי הרשויות", text: "איפה, ואיך מגיעים ברשת" },
      { icon: "🔐", title: "הזדהות ומעבר", text: "שיטה · מערכת רושמת" },
    ],
  },
};
